org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.244
loader_version_range=[1,)

mod_id=cobblemon_create_logistics
mod_name=Cobblemon Create Logistics
mod_license=MIT
mod_version=0.1.1
mod_group_id=dev.cobblemoncreate
mod_authors=runwater73-cpu
mod_description=Create logistics integration for Cobblemon couriers.

create_version=6.0.10-280
create_version_range=[6.0.10,)
cobblemon_project=MdwFAVRL
cobblemon_version=7otgw3aH
cobblemon_version_range=[1.8.1,)
kotlinforforge_project=ordsPcFz
kotlinforforge_version=uhJhCT7X
kotlinforforge_version_range=[5.3,)
